name: shopware-cli

env:
  EXTENSION_NAME: RuneLaenenTwoFactorAuth

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Shopware CLI
        uses: FriendsOfShopware/shopware-cli-action@v1

      - name: Build and Package Extension
        run: |
          rm -rf ./.github
          shopware-cli extension zip . --disable-git

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}
          path: ${{ env.EXTENSION_NAME }}.zip